/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Description
    /// </summary>
    public class GetCheckpointByTrackingIdOptions : BaseOptions
    {
        public GetCheckpointByTrackingIdOptions() { }

        public string Fields { get; set; }
        public string Lang { get; set; }

        public override List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            p.Add(new KeyValuePair<string, string>("fields", Fields));
            p.Add(new KeyValuePair<string, string>("lang", Lang));
            return p;
        }
    }

    /// <summary>
    /// Description
    /// </summary>
    public class GetCheckpointBySlugTrackingNumberOptions : BaseOptions
    {
        public GetCheckpointBySlugTrackingNumberOptions() { }

        public string Fields { get; set; }
        public string Lang { get; set; }
        public string TrackingAccountNumber { get; set; }
        public string TrackingOriginCountry { get; set; }
        public string TrackingDestinationCountry { get; set; }
        public string TrackingKey { get; set; }
        public string TrackingPostalCode { get; set; }
        public string TrackingShipDate { get; set; }
        public string TrackingState { get; set; }

        public override List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            p.Add(new KeyValuePair<string, string>("fields", Fields));
            p.Add(new KeyValuePair<string, string>("lang", Lang));
            p.Add(
                new KeyValuePair<string, string>("tracking_account_number", TrackingAccountNumber)
            );
            p.Add(
                new KeyValuePair<string, string>("tracking_origin_country", TrackingOriginCountry)
            );
            p.Add(
                new KeyValuePair<string, string>(
                    "tracking_destination_country",
                    TrackingDestinationCountry
                )
            );
            p.Add(new KeyValuePair<string, string>("tracking_key", TrackingKey));
            p.Add(new KeyValuePair<string, string>("tracking_postal_code", TrackingPostalCode));
            p.Add(new KeyValuePair<string, string>("tracking_ship_date", TrackingShipDate));
            p.Add(new KeyValuePair<string, string>("tracking_state", TrackingState));
            return p;
        }
    }
}
