/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

// Information about this assembly is defined by the following attributes.
// Change them to the values specific to your project.

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// The form "{Major}.{Minor}.*" will automatically update the build and revision,
// and "{Major}.{Minor}.{Build}.*" will update just the revision.

internal class AssemblyInformation
{
    public const string AssemblyInformationalVersion = "8.0.0";
}
