/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Description
    /// </summary>
    public class GetNotificationByTrackingIdOptions : BaseOptions
    {
        public GetNotificationByTrackingIdOptions() { }
    }

    /// <summary>
    /// Description
    /// </summary>
    public class AddNotificationByTrackingIdOptions : BaseOptions
    {
        public AddNotificationByTrackingIdOptions() { }

        public AddNotificationByTrackingIdRequest AddNotificationByTrackingIdRequest { get; set; }

        public override string GetBody()
        {
            string body = null;

            if (AddNotificationByTrackingIdRequest != null)
            {
                body = BaseResourceService.ToJson(AddNotificationByTrackingIdRequest);
            }
            return body;
        }
    }

    /// <summary>
    /// Description
    /// </summary>
    public class DeleteNotificationByTrackingIdOptions : BaseOptions
    {
        public DeleteNotificationByTrackingIdOptions() { }

        public DeleteNotificationByTrackingIdRequest DeleteNotificationByTrackingIdRequest { get; set; }

        public override string GetBody()
        {
            string body = null;

            if (DeleteNotificationByTrackingIdRequest != null)
            {
                body = BaseResourceService.ToJson(DeleteNotificationByTrackingIdRequest);
            }
            return body;
        }
    }

    /// <summary>
    /// Description
    /// </summary>
    public class GetNotificationBySlugTrackingNumberOptions : BaseOptions
    {
        public GetNotificationBySlugTrackingNumberOptions() { }

        public string TrackingAccountNumber { get; set; }
        public string TrackingOriginCountry { get; set; }
        public string TrackingDestinationCountry { get; set; }
        public string TrackingKey { get; set; }
        public string TrackingPostalCode { get; set; }
        public string TrackingShipDate { get; set; }
        public string TrackingState { get; set; }

        public override List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            p.Add(
                new KeyValuePair<string, string>("tracking_account_number", TrackingAccountNumber)
            );
            p.Add(
                new KeyValuePair<string, string>("tracking_origin_country", TrackingOriginCountry)
            );
            p.Add(
                new KeyValuePair<string, string>(
                    "tracking_destination_country",
                    TrackingDestinationCountry
                )
            );
            p.Add(new KeyValuePair<string, string>("tracking_key", TrackingKey));
            p.Add(new KeyValuePair<string, string>("tracking_postal_code", TrackingPostalCode));
            p.Add(new KeyValuePair<string, string>("tracking_ship_date", TrackingShipDate));
            p.Add(new KeyValuePair<string, string>("tracking_state", TrackingState));
            return p;
        }
    }

    /// <summary>
    /// Description
    /// </summary>
    public class AddNotificationBySlugTrackingNumberOptions : BaseOptions
    {
        public AddNotificationBySlugTrackingNumberOptions() { }

        public string TrackingAccountNumber { get; set; }
        public string TrackingOriginCountry { get; set; }
        public string TrackingDestinationCountry { get; set; }
        public string TrackingKey { get; set; }
        public string TrackingPostalCode { get; set; }
        public string TrackingShipDate { get; set; }
        public string TrackingState { get; set; }

        public override List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            p.Add(
                new KeyValuePair<string, string>("tracking_account_number", TrackingAccountNumber)
            );
            p.Add(
                new KeyValuePair<string, string>("tracking_origin_country", TrackingOriginCountry)
            );
            p.Add(
                new KeyValuePair<string, string>(
                    "tracking_destination_country",
                    TrackingDestinationCountry
                )
            );
            p.Add(new KeyValuePair<string, string>("tracking_key", TrackingKey));
            p.Add(new KeyValuePair<string, string>("tracking_postal_code", TrackingPostalCode));
            p.Add(new KeyValuePair<string, string>("tracking_ship_date", TrackingShipDate));
            p.Add(new KeyValuePair<string, string>("tracking_state", TrackingState));
            return p;
        }

        public AddNotificationBySlugTrackingNumberRequest AddNotificationBySlugTrackingNumberRequest { get; set; }

        public override string GetBody()
        {
            string body = null;

            if (AddNotificationBySlugTrackingNumberRequest != null)
            {
                body = BaseResourceService.ToJson(AddNotificationBySlugTrackingNumberRequest);
            }
            return body;
        }
    }

    /// <summary>
    /// Description
    /// </summary>
    public class DeleteNotificationBySlugTrackingNumberOptions : BaseOptions
    {
        public DeleteNotificationBySlugTrackingNumberOptions() { }

        public string TrackingAccountNumber { get; set; }
        public string TrackingOriginCountry { get; set; }
        public string TrackingDestinationCountry { get; set; }
        public string TrackingKey { get; set; }
        public string TrackingPostalCode { get; set; }
        public string TrackingShipDate { get; set; }
        public string TrackingState { get; set; }

        public override List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            p.Add(
                new KeyValuePair<string, string>("tracking_account_number", TrackingAccountNumber)
            );
            p.Add(
                new KeyValuePair<string, string>("tracking_origin_country", TrackingOriginCountry)
            );
            p.Add(
                new KeyValuePair<string, string>(
                    "tracking_destination_country",
                    TrackingDestinationCountry
                )
            );
            p.Add(new KeyValuePair<string, string>("tracking_key", TrackingKey));
            p.Add(new KeyValuePair<string, string>("tracking_postal_code", TrackingPostalCode));
            p.Add(new KeyValuePair<string, string>("tracking_ship_date", TrackingShipDate));
            p.Add(new KeyValuePair<string, string>("tracking_state", TrackingState));
            return p;
        }

        public DeleteNotificationBySlugTrackingNumberRequest DeleteNotificationBySlugTrackingNumberRequest { get; set; }

        public override string GetBody()
        {
            string body = null;

            if (DeleteNotificationBySlugTrackingNumberRequest != null)
            {
                body = BaseResourceService.ToJson(DeleteNotificationBySlugTrackingNumberRequest);
            }
            return body;
        }
    }
}
