/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Net.Http;

namespace AfterShipTracking
{
    public class NotificationService : BaseResourceService
    {
        IHttpClient HttpClient;

        public NotificationService(IHttpClient httpClient)
        {
            this.HttpClient = httpClient;
        }

        public Notification GetNotificationByTrackingId(
            string trackingId,
            GetNotificationByTrackingIdOptions? options = null
        )
        {
            string path = $"/tracking/2024-04/notifications/{trackingId}";
            if (string.IsNullOrEmpty(trackingId))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `tracking_id` is invalid"
                );
            }
            Request request = new Request(HttpMethod.Get, path, options);

            var response = this.HttpClient.MakeRequest(request);
            return ProcessResponseData(response, new GetNotificationByTrackingIdAdapter());
        }

        public Notification AddNotificationByTrackingId(
            string trackingId,
            AddNotificationByTrackingIdOptions? options = null
        )
        {
            string path = $"/tracking/2024-04/notifications/{trackingId}/add";
            if (string.IsNullOrEmpty(trackingId))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `tracking_id` is invalid"
                );
            }
            Request request = new Request(HttpMethod.Post, path, options);

            var response = this.HttpClient.MakeRequest(request);
            return ProcessResponseData(response, new AddNotificationByTrackingIdAdapter());
        }

        public Notification DeleteNotificationByTrackingId(
            string trackingId,
            DeleteNotificationByTrackingIdOptions? options = null
        )
        {
            string path = $"/tracking/2024-04/notifications/{trackingId}/remove";
            if (string.IsNullOrEmpty(trackingId))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `tracking_id` is invalid"
                );
            }
            Request request = new Request(HttpMethod.Post, path, options);

            var response = this.HttpClient.MakeRequest(request);
            return ProcessResponseData(response, new DeleteNotificationByTrackingIdAdapter());
        }

        public Notification GetNotificationBySlugTrackingNumber(
            string slug,
            string trackingNumber,
            GetNotificationBySlugTrackingNumberOptions? options = null
        )
        {
            string path = $"/tracking/2024-04/notifications/{slug}/{trackingNumber}";
            if (string.IsNullOrEmpty(slug))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `slug` is invalid"
                );
            }
            if (string.IsNullOrEmpty(trackingNumber))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `tracking_number` is invalid"
                );
            }
            Request request = new Request(HttpMethod.Get, path, options);

            var response = this.HttpClient.MakeRequest(request);
            return ProcessResponseData(response, new GetNotificationBySlugTrackingNumberAdapter());
        }

        public Notification AddNotificationBySlugTrackingNumber(
            string slug,
            string trackingNumber,
            AddNotificationBySlugTrackingNumberOptions? options = null
        )
        {
            string path = $"/tracking/2024-04/notifications/{slug}/{trackingNumber}/add";
            if (string.IsNullOrEmpty(slug))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `slug` is invalid"
                );
            }
            if (string.IsNullOrEmpty(trackingNumber))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `tracking_number` is invalid"
                );
            }
            Request request = new Request(HttpMethod.Post, path, options);

            var response = this.HttpClient.MakeRequest(request);
            return ProcessResponseData(response, new AddNotificationBySlugTrackingNumberAdapter());
        }

        public Notification DeleteNotificationBySlugTrackingNumber(
            string slug,
            string trackingNumber,
            DeleteNotificationBySlugTrackingNumberOptions? options = null
        )
        {
            string path = $"/tracking/2024-04/notifications/{slug}/{trackingNumber}/remove";
            if (string.IsNullOrEmpty(slug))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `slug` is invalid"
                );
            }
            if (string.IsNullOrEmpty(trackingNumber))
            {
                throw ErrorCode.GenSDKError(
                    ErrorCode.REQUEST_ERROR,
                    "request error" + ": `tracking_number` is invalid"
                );
            }
            Request request = new Request(HttpMethod.Post, path, options);

            var response = this.HttpClient.MakeRequest(request);
            return ProcessResponseData(
                response,
                new DeleteNotificationBySlugTrackingNumberAdapter()
            );
        }
    }
}
