/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using System;

namespace Tracking;

public class AfterShipError : Exception
{
    protected string errorCode;
    protected string message;
    protected int? metaCode;
    protected object responseBody;
    protected int? statusCode;

    public AfterShipError(string message, string errorCode, int? statusCode, int? metaCode, object responseBody = null)
        : base(message)
    {
        this.metaCode = metaCode;
        this.message = message;
        this.errorCode = errorCode;
        this.statusCode = statusCode;
        this.responseBody = responseBody;
    }

    public string ErrorCode => errorCode;

    public int? MetaCode => metaCode;

    public int? StatusCode => statusCode;

    public object ResponseBody => responseBody;
}