/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

namespace Tracking;

public interface IHttpClient
{
    public Response MakeRequest(Request request);
}