/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

namespace Tracking;

/// <summary>
///     Description
/// </summary>
public class GetUserCouriersOptions : BaseOptions
{
}

/// <summary>
///     Description
/// </summary>
public class DetectCourierOptions : BaseOptions
{
    public DetectCourierRequest DetectCourierRequest { get; set; }

    public override string GetBody()
    {
        string body = null;

        if (DetectCourierRequest != null) body = BaseResourceService.ToJson(DetectCourierRequest);
        return body;
    }
}

/// <summary>
///     Description
/// </summary>
public class GetAllCouriersOptions : BaseOptions
{
}