/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using System.Net.Http;

namespace Tracking;

public class CourierService : BaseResourceService
{
    private readonly IHttpClient HttpClient;

    public CourierService(IHttpClient httpClient)
    {
        HttpClient = httpClient;
    }

    public GetUserCouriersResponse GetUserCouriers(GetUserCouriersOptions? options = null)
    {
        var path = "/tracking/2024-04/couriers";
        var request = new Request(
            HttpMethod.Get,
            path,
            options
        );

        var response = HttpClient.MakeRequest(request);
        return ProcessData<GetUserCouriersResponse>(response);
    }

    public DetectCourierResponse DetectCourier(DetectCourierOptions? options = null)
    {
        var path = "/tracking/2024-04/couriers/detect";
        var request = new Request(
            HttpMethod.Post,
            path,
            options
        );

        var response = HttpClient.MakeRequest(request);
        return ProcessData<DetectCourierResponse>(response);
    }

    public GetAllCouriersResponse GetAllCouriers(GetAllCouriersOptions? options = null)
    {
        var path = "/tracking/2024-04/couriers/all";
        var request = new Request(
            HttpMethod.Get,
            path,
            options
        );

        var response = HttpClient.MakeRequest(request);
        return ProcessData<GetAllCouriersResponse>(response);
    }
}