/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace AfterShipTracking
{
    /// <summary>
    /// Tracking adapter for legacy object convert to new model object
    /// </summary>
    public class GetNotificationByTrackingIdAdapter
        : IAdapter<Notification, GetNotificationByTrackingIdResponse>
    {
        public Notification Adapt(GetNotificationByTrackingIdResponse source)
        {
            return source.Notification;
        }
    }

    /// <summary>
    /// Tracking adapter for legacy object convert to new model object
    /// </summary>
    public class AddNotificationByTrackingIdAdapter
        : IAdapter<Notification, AddNotificationByTrackingIdResponse>
    {
        public Notification Adapt(AddNotificationByTrackingIdResponse source)
        {
            return source.Notification;
        }
    }

    /// <summary>
    /// Tracking adapter for legacy object convert to new model object
    /// </summary>
    public class DeleteNotificationByTrackingIdAdapter
        : IAdapter<Notification, DeleteNotificationByTrackingIdResponse>
    {
        public Notification Adapt(DeleteNotificationByTrackingIdResponse source)
        {
            return source.Notification;
        }
    }

    /// <summary>
    /// Tracking adapter for legacy object convert to new model object
    /// </summary>
    public class GetNotificationBySlugTrackingNumberAdapter
        : IAdapter<Notification, GetNotificationBySlugTrackingNumberResponse>
    {
        public Notification Adapt(GetNotificationBySlugTrackingNumberResponse source)
        {
            return source.Notification;
        }
    }

    /// <summary>
    /// Tracking adapter for legacy object convert to new model object
    /// </summary>
    public class AddNotificationBySlugTrackingNumberAdapter
        : IAdapter<Notification, AddNotificationBySlugTrackingNumberResponse>
    {
        public Notification Adapt(AddNotificationBySlugTrackingNumberResponse source)
        {
            return source.Notification;
        }
    }

    /// <summary>
    /// Tracking adapter for legacy object convert to new model object
    /// </summary>
    public class DeleteNotificationBySlugTrackingNumberAdapter
        : IAdapter<Notification, DeleteNotificationBySlugTrackingNumberResponse>
    {
        public Notification Adapt(DeleteNotificationBySlugTrackingNumberResponse source)
        {
            return source.Notification;
        }
    }
}
