/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using Newtonsoft.Json;

namespace Tracking;

public class BaseResponse
{
    [JsonProperty("meta")] public Meta Meta { get; set; }

    [JsonProperty("data")] public object Data { get; set; }
}