/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    ///
    /// </summary>
    public class AddNotificationByTrackingIdRequest
    {
        /// <summary>
        ///  Notification Notification request object
        /// </summary>
        [JsonProperty("notification", NullValueHandling = NullValueHandling.Ignore)]
        public NotificationRequestV1? Notification { get; set; }

        public AddNotificationByTrackingIdRequest() { }
    }
}
