/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    ///
    /// </summary>
    public class DeleteTrackingByIdResponse
    {
        /// <summary>
        ///  Tracking Partial tracking model
        /// </summary>
        [JsonProperty("tracking")]
        public PartialDeleteTracking? Tracking { get; set; }

        public DeleteTrackingByIdResponse() { }
    }
}
