/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class  GetTrackingsResponse
    {
        /// <summary>
        ///  Page Page to show. (Default: 1)
        /// </summary>
        [JsonProperty("page")]
        public int?  Page { get; set; }
        /// <summary>
        ///  Limit Number of trackings each page contain. (Default: 100, Max: 200)
        /// </summary>
        [JsonProperty("limit")]
        public int?  Limit { get; set; }
        /// <summary>
        ///  Count Number of returned trackings
        /// </summary>
        [JsonProperty("count")]
        public int?  Count { get; set; }
        /// <summary>
        ///  Keyword Search the content of the tracking record fields: `tracking_number`, `title`, `order_id`, `customer_name`, `custom_fields`, `order_id`, `emails`, `smses`
        /// </summary>
        [JsonProperty("keyword")]
        public string?  Keyword { get; set; }
        /// <summary>
        ///  Slug Unique 
        /// </summary>
        [JsonProperty("slug")]
        public string?  Slug { get; set; }
        /// <summary>
        ///  Origin Origin country/region of trackings. Use 
        /// </summary>
        [JsonProperty("origin")]
        public string? [] Origin { get; set; }
        /// <summary>
        ///  Destination Destination country/region of trackings. Use 
        /// </summary>
        [JsonProperty("destination")]
        public string? [] Destination { get; set; }
        /// <summary>
        ///  Tag Current status of tracking. (
        /// </summary>
        [JsonProperty("tag")]
        public TagV1?  Tag { get; set; }
        /// <summary>
        ///  CreatedAtMin Start date and time of trackings created. AfterShip only stores data of 120 days.
        /// </summary>
        [JsonProperty("created_at_min")]
        public string?  CreatedAtMin { get; set; }
        /// <summary>
        ///  CreatedAtMax End date and time of trackings created.
        /// </summary>
        [JsonProperty("created_at_max")]
        public string?  CreatedAtMax { get; set; }
        /// <summary>
        ///  LastUpdatedAt Date and time the tracking was last updated
        /// </summary>
        [JsonProperty("last_updated_at")]
        public string?  LastUpdatedAt { get; set; }
        /// <summary>
        ///  ReturnToSender Whether or not the shipment is returned to sender. Value is `true` when any of its checkpoints has subtag `Exception_010` (returning to sender) or `Exception_011` (returned to sender). Otherwise value is `false`
        /// </summary>
        [JsonProperty("return_to_sender")]
        public bool? [] ReturnToSender { get; set; }
        /// <summary>
        ///  CourierDestinationCountryIso3 Destination country/region of the tracking detected from the courier. ISO Alpha-3 (three letters). Value will be `null` if the courier doesn't provide the destination country.
        /// </summary>
        [JsonProperty("courier_destination_country_iso3")]
        public string? [] CourierDestinationCountryIso3 { get; set; }
        /// <summary>
        ///  Trackings Array of 
        /// </summary>
        [JsonProperty("trackings")]
        public Tracking? [] Trackings { get; set; }
        public GetTrackingsResponse()
        {
        }
    }
    
    /// <summary>
    /// 
    /// </summary>
    public class  GetTrackingsResponseTrackingListData
    {
        /// <summary>
        ///  Trackings 
        /// </summary>
        [JsonProperty("trackings")]
        public Tracking? [] Trackings { get; set; }
        /// <summary>
        ///  Pagination 
        /// </summary>
        [JsonProperty("pagination")]
        public PaginationPage?  Pagination { get; set; }

        public GetTrackingsResponseTrackingListData()
        {
        }
    }
}
