/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class  GetUserCouriersResponse
    {
        /// <summary>
        ///  Total Total count of courier objects
        /// </summary>
        [JsonProperty("total")]
        public int?  Total { get; set; }
        /// <summary>
        ///  Couriers Array of  object.
        /// </summary>
        [JsonProperty("couriers")]
        public Courier? [] Couriers { get; set; }
        public GetUserCouriersResponse()
        {
        }
    }
    
}
