/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Notification request object
    /// </summary>
    public class NotificationRequestV1
    {
        /// <summary>
        ///  Emails Email address(es) to receive email notifications.Accept either array or comma separated as input.
        /// </summary>
        [JsonProperty("emails", NullValueHandling = NullValueHandling.Ignore)]
        public string?[] Emails { get; set; }

        /// <summary>
        ///  Smses The phone number(s) to receive sms notifications.  Enter `+` and `area code` before phone number.Accept either array or comma separated as input.
        /// </summary>
        [JsonProperty("smses", NullValueHandling = NullValueHandling.Ignore)]
        public string?[] Smses { get; set; }

        public NotificationRequestV1() { }
    }
}
