/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    ///
    /// </summary>
    public class UpdateTrackingBySlugTrackingNumberResponse
    {
        /// <summary>
        ///  Tracking Object describes the tracking information.<div style="display:none; height: 0"></div>
        /// </summary>
        [JsonProperty("tracking")]
        public Tracking? Tracking { get; set; }

        public UpdateTrackingBySlugTrackingNumberResponse() { }
    }
}
