/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Description
    /// </summary>
    public class DetectCourierOptions : BaseOptions
    {
        public  DetectCourierOptions()
        {
        }


        public DetectCourierRequest DetectCourierRequest { get; set; }

        override public string GetBody()
        {
            string body = null;

            if ( DetectCourierRequest != null)
            {
                body = BaseResourceService.ToJson(DetectCourierRequest);
            }
            return body;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class GetAllCouriersOptions : BaseOptions
    {
        public  GetAllCouriersOptions()
        {
        }


    }
    /// <summary>
    /// Description
    /// </summary>
    public class GetUserCouriersOptions : BaseOptions
    {
        public  GetUserCouriersOptions()
        {
        }


    }
}
