/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace AfterShipTracking
{
    public interface IAdapter<TTarget, TSource>
    {
        TTarget Adapt(TSource source);
    }

    public static class Converter
    {
        public static TTarget Convert<TTarget, TSource>(TSource source, IAdapter<TTarget, TSource> adapter)
        {
            return adapter.Adapt(source);
        }
    }
}
