/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
namespace AfterShipTracking
{
    public interface IHttpClient
    {
        public Response MakeRequest(Request request);
    }
}
