/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Net;
using Headers = System.Net.Http.Headers.HttpResponseHeaders;

namespace AfterShipTracking
{
    public class Response
    {
        /// <summary>
        /// HTTP status code
        /// </summary>
        public HttpStatusCode StatusCode { get; }

        /// <summary>
        /// Content string
        /// </summary>
        public string Content { get; }

        /// <summary>
        /// Headers
        /// </summary>
        public Headers Headers { get; }

        internal int NumRetries { get; set; }

        /// <summary>
        /// Create a new Response
        /// </summary>
        /// <param name="statusCode">HTTP status code</param>
        /// <param name="content">Content string</param>
        /// <param name="headers">Headers</param>
        public Response(HttpStatusCode statusCode, Headers headers, string content)
        {
            StatusCode = statusCode;
            Headers = headers;
            Content = content;
        }
    }
}
