/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using Newtonsoft.Json;

namespace Tracking;

/// <summary>
/// </summary>
public class AddNotificationBySlugTrackingNumberResponse
{
    /// <summary>
    ///     Notification Object describes the notification information.
    /// </summary>
    [JsonProperty("notification")]
    public Notification? Notification { get; set; }
}