/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using Newtonsoft.Json;

namespace Tracking;

/// <summary>
/// </summary>
public class GetTrackingBySlugTrackingNumberResponse
{
    /// <summary>
    ///     Tracking Object describes the tracking information.<div style="display:none; height: 0"></div>
    /// </summary>
    [JsonProperty("tracking")]
    public Tracking? Tracking { get; set; }
}