/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using Newtonsoft.Json;

namespace Tracking;

/// <summary>
/// </summary>
public class GetUserCouriersResponse
{
    /// <summary>
    ///     Total Total count of courier objects
    /// </summary>
    [JsonProperty("total")]
    public int? Total { get; set; }

    /// <summary>
    ///     Couriers Array of  object.
    /// </summary>
    [JsonProperty("couriers")]
    public Courier?[] Couriers { get; set; }
}