/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using Newtonsoft.Json;

namespace Tracking;

/// <summary>
///     Partial tracking
/// </summary>
public class PartialUpdateTracking
{
    /// <summary>
    ///     Id A unique identifier generated by AfterShip for the tracking.
    /// </summary>
    [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
    public string? Id { get; set; }

    /// <summary>
    ///     TrackingNumber Tracking number.
    /// </summary>
    [JsonProperty("tracking_number", NullValueHandling = NullValueHandling.Ignore)]
    public string? TrackingNumber { get; set; }

    /// <summary>
    ///     Slug Unique code of courier. Get the slugs from .
    /// </summary>
    [JsonProperty("slug", NullValueHandling = NullValueHandling.Ignore)]
    public string? Slug { get; set; }

    /// <summary>
    ///     TrackingAccountNumber Additional field required by some carriers to retrieve the tracking info. The shipper’s
    ///     carrier account number. Refer to our article on  for more details.
    /// </summary>
    [JsonProperty("tracking_account_number", NullValueHandling = NullValueHandling.Ignore)]
    public string? TrackingAccountNumber { get; set; }

    /// <summary>
    ///     TrackingOriginCountry Additional field required by some carriers to retrieve the tracking info. The origin
    ///     country/region of the shipment. Refer to our article on  for more details.
    /// </summary>
    [JsonProperty("tracking_origin_country", NullValueHandling = NullValueHandling.Ignore)]
    public string? TrackingOriginCountry { get; set; }

    /// <summary>
    ///     TrackingDestinationCountry Additional field required by some carriers to retrieve the tracking info. The
    ///     destination country/region of the shipment. Refer to our article on  for more details.
    /// </summary>
    [JsonProperty("tracking_destination_country", NullValueHandling = NullValueHandling.Ignore)]
    public string? TrackingDestinationCountry { get; set; }

    /// <summary>
    ///     TrackingKey Additional field required by some carriers to retrieve the tracking info. A type of tracking credential
    ///     required by some carriers. Refer to our article on  for more details.
    /// </summary>
    [JsonProperty("tracking_key", NullValueHandling = NullValueHandling.Ignore)]
    public string? TrackingKey { get; set; }

    /// <summary>
    ///     TrackingShipDate Additional field required by some carriers to retrieve the tracking info. The date the shipment
    ///     was sent, using the format YYYYMMDD. Refer to our article on  for more details.
    /// </summary>
    [JsonProperty("tracking_ship_date", NullValueHandling = NullValueHandling.Ignore)]
    public string? TrackingShipDate { get; set; }

    /// <summary>
    ///     TrackingPostalCode Additional field required by some carriers to retrieve the tracking info. The postal code of the
    ///     recipient’s address. Refer to our article on  for more details.
    /// </summary>
    [JsonProperty("tracking_postal_code", NullValueHandling = NullValueHandling.Ignore)]
    public string? TrackingPostalCode { get; set; }

    /// <summary>
    ///     TrackingState Additional field required by some carriers to retrieve the tracking info. The state/province of the
    ///     recipient’s address. Refer to our article on  for more details.
    /// </summary>
    [JsonProperty("tracking_state", NullValueHandling = NullValueHandling.Ignore)]
    public string? TrackingState { get; set; }

    /// <summary>
    ///     Active Whether or not AfterShip will continue tracking the shipments. Value is `false` when tag (status) is
    ///     `Delivered`, `Expired`, or further updates for 30 days since last update.
    /// </summary>
    [JsonProperty("active", NullValueHandling = NullValueHandling.Ignore)]
    public bool? Active { get; set; }
}