/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using Newtonsoft.Json;

namespace Tracking;

/// <summary>
/// </summary>
public class PredictBatchResponse
{
    /// <summary>
    ///     EstimatedDeliveryDates
    /// </summary>
    [JsonProperty("estimated_delivery_dates")]
    public EstimatedDeliveryDateResponse[] EstimatedDeliveryDates { get; set; }
}