/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using Newtonsoft.Json;

namespace Tracking;

/// <summary>
///     Tracking response for returning single tracking when deleting tracking
/// </summary>
public class TrackingDeleteResponseV1
{
    /// <summary>
    ///     Meta Meta data
    /// </summary>
    [JsonProperty("meta")]
    public MetaV1 Meta { get; set; }

    /// <summary>
    ///     Data
    /// </summary>
    [JsonProperty("data")]
    public DataTrackingDeleteResponseV1 Data { get; set; }
}

/// <summary>
/// </summary>
public class DataTrackingDeleteResponseV1
{
    /// <summary>
    ///     Tracking Partial tracking model
    /// </summary>
    [JsonProperty("tracking", NullValueHandling = NullValueHandling.Ignore)]
    public PartialDeleteTracking? Tracking { get; set; }
}