/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using System.Collections.Generic;

namespace Tracking;

/// <summary>
///     Description
/// </summary>
public class GetNotificationByTrackingIdOptions : BaseOptions
{
}

/// <summary>
///     Description
/// </summary>
public class GetNotificationBySlugTrackingNumberOptions : BaseOptions
{
    public string TrackingAccountNumber { get; set; }
    public string TrackingOriginCountry { get; set; }
    public string TrackingDestinationCountry { get; set; }
    public string TrackingKey { get; set; }
    public string TrackingPostalCode { get; set; }
    public string TrackingShipDate { get; set; }
    public string TrackingState { get; set; }

    public override List<KeyValuePair<string, string>> GetQueryParams()
    {
        var p = new List<KeyValuePair<string, string>>();
        p.Add(new KeyValuePair<string, string>("tracking_account_number", TrackingAccountNumber));
        p.Add(new KeyValuePair<string, string>("tracking_origin_country", TrackingOriginCountry));
        p.Add(new KeyValuePair<string, string>("tracking_destination_country", TrackingDestinationCountry));
        p.Add(new KeyValuePair<string, string>("tracking_key", TrackingKey));
        p.Add(new KeyValuePair<string, string>("tracking_postal_code", TrackingPostalCode));
        p.Add(new KeyValuePair<string, string>("tracking_ship_date", TrackingShipDate));
        p.Add(new KeyValuePair<string, string>("tracking_state", TrackingState));
        return p;
    }
}

/// <summary>
///     Description
/// </summary>
public class AddNotificationByTrackingIdOptions : BaseOptions
{
    public AddNotificationByTrackingIdRequest AddNotificationByTrackingIdRequest { get; set; }

    public override string GetBody()
    {
        string body = null;

        if (AddNotificationByTrackingIdRequest != null)
            body = BaseResourceService.ToJson(AddNotificationByTrackingIdRequest);
        return body;
    }
}

/// <summary>
///     Description
/// </summary>
public class DeleteNotificationByTrackingIdOptions : BaseOptions
{
    public DeleteNotificationByTrackingIdRequest DeleteNotificationByTrackingIdRequest { get; set; }

    public override string GetBody()
    {
        string body = null;

        if (DeleteNotificationByTrackingIdRequest != null)
            body = BaseResourceService.ToJson(DeleteNotificationByTrackingIdRequest);
        return body;
    }
}

/// <summary>
///     Description
/// </summary>
public class AddNotificationBySlugTrackingNumberOptions : BaseOptions
{
    public string TrackingAccountNumber { get; set; }
    public string TrackingOriginCountry { get; set; }
    public string TrackingDestinationCountry { get; set; }
    public string TrackingKey { get; set; }
    public string TrackingPostalCode { get; set; }
    public string TrackingShipDate { get; set; }
    public string TrackingState { get; set; }
    public AddNotificationBySlugTrackingNumberRequest AddNotificationBySlugTrackingNumberRequest { get; set; }

    public override List<KeyValuePair<string, string>> GetQueryParams()
    {
        var p = new List<KeyValuePair<string, string>>();
        p.Add(new KeyValuePair<string, string>("tracking_account_number", TrackingAccountNumber));
        p.Add(new KeyValuePair<string, string>("tracking_origin_country", TrackingOriginCountry));
        p.Add(new KeyValuePair<string, string>("tracking_destination_country", TrackingDestinationCountry));
        p.Add(new KeyValuePair<string, string>("tracking_key", TrackingKey));
        p.Add(new KeyValuePair<string, string>("tracking_postal_code", TrackingPostalCode));
        p.Add(new KeyValuePair<string, string>("tracking_ship_date", TrackingShipDate));
        p.Add(new KeyValuePair<string, string>("tracking_state", TrackingState));
        return p;
    }

    public override string GetBody()
    {
        string body = null;

        if (AddNotificationBySlugTrackingNumberRequest != null)
            body = BaseResourceService.ToJson(AddNotificationBySlugTrackingNumberRequest);
        return body;
    }
}

/// <summary>
///     Description
/// </summary>
public class DeleteNotificationBySlugTrackingNumberOptions : BaseOptions
{
    public string TrackingAccountNumber { get; set; }
    public string TrackingOriginCountry { get; set; }
    public string TrackingDestinationCountry { get; set; }
    public string TrackingKey { get; set; }
    public string TrackingPostalCode { get; set; }
    public string TrackingShipDate { get; set; }
    public string TrackingState { get; set; }
    public DeleteNotificationBySlugTrackingNumberRequest DeleteNotificationBySlugTrackingNumberRequest { get; set; }

    public override List<KeyValuePair<string, string>> GetQueryParams()
    {
        var p = new List<KeyValuePair<string, string>>();
        p.Add(new KeyValuePair<string, string>("tracking_account_number", TrackingAccountNumber));
        p.Add(new KeyValuePair<string, string>("tracking_origin_country", TrackingOriginCountry));
        p.Add(new KeyValuePair<string, string>("tracking_destination_country", TrackingDestinationCountry));
        p.Add(new KeyValuePair<string, string>("tracking_key", TrackingKey));
        p.Add(new KeyValuePair<string, string>("tracking_postal_code", TrackingPostalCode));
        p.Add(new KeyValuePair<string, string>("tracking_ship_date", TrackingShipDate));
        p.Add(new KeyValuePair<string, string>("tracking_state", TrackingState));
        return p;
    }

    public override string GetBody()
    {
        string body = null;

        if (DeleteNotificationBySlugTrackingNumberRequest != null)
            body = BaseResourceService.ToJson(DeleteNotificationBySlugTrackingNumberRequest);
        return body;
    }
}