/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Description
    /// </summary>
    public class PredictBatchOptions : BaseOptions
    {
        public  PredictBatchOptions()
        {
        }


        public PredictBatchRequest PredictBatchRequest { get; set; }

        override public string GetBody()
        {
            string body = null;

            if ( PredictBatchRequest != null)
            {
                body = BaseResourceService.ToJson(PredictBatchRequest);
            }
            return body;
        }
    }
}
