/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

using System.Net.Http;

namespace Tracking;

public class EstimatedDeliveryDateService : BaseResourceService
{
    private readonly IHttpClient HttpClient;

    public EstimatedDeliveryDateService(IHttpClient httpClient)
    {
        HttpClient = httpClient;
    }

    public PredictBatchResponse PredictBatch(PredictBatchOptions? options = null)
    {
        var path = "/tracking/2024-04/estimated-delivery-date/predict-batch";
        var request = new Request(
            HttpMethod.Post,
            path,
            options
        );

        var response = HttpClient.MakeRequest(request);
        return ProcessData<PredictBatchResponse>(response);
    }
}