/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

namespace Tracking;

/// <summary>
///     Description
/// </summary>
public class PredictBatchOptions : BaseOptions
{
    public PredictBatchRequest PredictBatchRequest { get; set; }

    public override string GetBody()
    {
        string body = null;

        if (PredictBatchRequest != null) body = BaseResourceService.ToJson(PredictBatchRequest);
        return body;
    }
}