/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    public class BaseResponse
    {
        [JsonProperty("meta")]
        public Meta Meta { get; set; }

        [JsonProperty("data")]
        public Object Data { get; set; }
    }
}
