/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using Newtonsoft.Json;

namespace AfterShipTracking
{
    public class Meta
    {
        [JsonProperty("code")]
        public int? Code { get; set; }
        [JsonProperty("type")]
        public string? Type { get; set; }
        [JsonProperty("message")]
        public string? Message { get; set; }

        public Meta(int code, string type, string message)
        {
            Code = code;
            Type = type;
            Message = message;
        }
    }
}

