/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;

namespace AfterShipTracking
{
    public class AfterShipError : Exception
    {
        protected string errorCode;
        protected int? metaCode;
        protected int? statusCode;
        protected string message;
        protected object responseBody;

        public AfterShipError(string message, string errorCode, int? statusCode, int? metaCode, object responseBody = null)
        : base(message)
        {
            this.metaCode = metaCode;
            this.message = message;
            this.errorCode = errorCode;
            this.statusCode = statusCode;
            this.responseBody = responseBody;
        }

        public string ErrorCode
        {
            get { return errorCode; }
        }

        public int? MetaCode
        {
            get { return metaCode; }
        }

        public int? StatusCode
        {
            get { return statusCode; }
        }

        public object ResponseBody
        {
            get { return responseBody; }
        }
    }
}
